#!/usr/bin/env bash
# creates the app's release signing key and the android/key.properties that
# points at it. run this ONCE, ever.
#
# the key is the app's identity: android refuses to update an app signed by a
# different key, and f-droid/izzyondroid pin it per app. losing it means every
# user has to uninstall and lose their veilid identity and local lists, so back
# up both the keystore and its passwords somewhere durable before releasing.
# neither file is committed (see android/.gitignore).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
KEYSTORE="${VEILIST_KEYSTORE:-$ROOT/android/veilist-release.jks}"
ALIAS="${VEILIST_KEY_ALIAS:-veilist}"
PROPERTIES="$ROOT/android/key.properties"
# ~27 years: the key must outlive every release, and a key that expires strands
# the app the same way a lost one does.
VALIDITY_DAYS=10000

command -v keytool >/dev/null || { echo "!! keytool not found (install a jdk)" >&2; exit 1; }

if [ -e "$KEYSTORE" ]; then
  echo "!! $KEYSTORE already exists - refusing to overwrite the release key" >&2
  echo "   (delete it deliberately if you are certain it was never published)" >&2
  exit 1
fi

echo "== creating $KEYSTORE (alias '$ALIAS')"
echo "   choose a strong password; you will need it for every release."
keytool -genkeypair -v \
  -keystore "$KEYSTORE" \
  -alias "$ALIAS" \
  -keyalg RSA -keysize 4096 \
  -validity "$VALIDITY_DAYS" \
  -dname "CN=veilist, O=veilist, C=US"

# keytool prompts for the store password; the key inherits it, which is what
# gradle expects when keyPassword and storePassword match.
read -r -s -p "re-enter that password to write key.properties: " PASSWORD
echo

umask 077
cat >"$PROPERTIES" <<EOF
# generated by scripts/make_release_key.sh - never commit this file.
storeFile=$KEYSTORE
storePassword=$PASSWORD
keyAlias=$ALIAS
keyPassword=$PASSWORD
EOF

echo
echo "== wrote $PROPERTIES (gitignored)"
echo "== certificate fingerprint (this is the app's identity from now on):"
keytool -list -v -keystore "$KEYSTORE" -alias "$ALIAS" -storepass "$PASSWORD" |
  grep "SHA256:"
echo
echo "next:"
echo "  1. back up $KEYSTORE and the password offline."
echo "  2. add these github actions secrets for the release workflow:"
echo "       VEILIST_KEYSTORE_BASE64  = base64 -w0 $KEYSTORE"
echo "       VEILIST_KEYSTORE_PASSWORD, VEILIST_KEY_ALIAS, VEILIST_KEY_PASSWORD"
echo "  3. see DISTRIBUTION.md for the release and store-submission flow."
